### ISSUE TITLE
Add virtual category with installer

### ISSUE THREAD

**Issue by madonzy** [Smile-SA/elasticsuite#395]
I want to install virtual category with an installer (InstallData.php). (Only while installing Magento)

### Preconditions
Linux debian-8 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux

Magento Version: 2.1.4 CE
ElasticSuite Version : 2.3.4
Environment : default

### Steps to reproduce
1. I added sequence to my module **Smile_ElasticsuiteVirtualCategory**
2. php bin/magento setup:install ...

### Expected result
All modules installed successfully

### Actual result
I have an error:
```
Attribute with attributeCode "use_name_in_product_search" does not exist. 
```

If I don't add the sequence, then the category is added but fields **is_virtual_category** and **virtual_category_root** aren't set. I add the category like that:
```
$category = $this->categoryFactory->create();
$category
    ->setName('Test')
    ->setParentId($parentCategory->getId())
    ->setIsActive(true)
    ->setIncludeInMenu(false)
    ->setCustomAttributes([
        'is_virtual_category'   => '1',
        'url_key'               => 'test',
        'virtual_category_root' => $parentCategory->getParentCategory()->getId(),
    ]);

$this->categoryRepository->save($category);
```

**Comment by romainruaud** [comment]
Hello @madonzy 

For me this is due to Magento not cleaning the EAV cache when adding an attribute via ```addAttribute``` in setups.

Please could you give a try to the PR https://github.com/Smile-SA/elasticsuite/pull/397 and tell me if this solves the issue ?

Best regards

**Comment by romainruaud** [comment]
I just updated the PR.

I was able to reproduce your bug on a "raw" install from Magento sources when having setup files which were creating categories.

You are right, adding a sequence to elasticsuite modules is not enough, so I added a cleaning of EAV cache manually after creating the attributes, since Magento does not do it when using addAttribute.

Feel free to test it and give us comments.

BR

**Comment by madonzy** [comment]
@romainruaud I've added `$this->cacheTypeList->cleanType('eav');` on the very beginning of installation script and nothing changed. The same error.

**Comment by romainruaud** [comment]
@madonzy please consider testing the fix by switching to my branch and not implementing your own fix by inspirating with mine.

My branch is working when launching Magento install based on one of our project containing categories creation in Setup files. This was crashing before my fix with the same error as yours. So I think I fixed the point.

Let me know,

**Comment by madonzy** [comment]
@romainruaud how can I switch to "your" branch? What exactly do you mean? Please provide some steps, because I'm not really understand you.

**Comment by romainruaud** [comment]
You could do either : 

- require my branch via composer, by doing this : http://stackoverflow.com/a/13500676

- or just report the modifications I made in this branch to the instance you are testing the install process, by writing directly on the module files, just for testing purposes.

Then try again to run your bin/magento setup:install and tell me if this does solve the issue.

Regards,

**Comment by madonzy** [comment]
Still not clear... What is your branch? What did you do? Where? Is it official fix? maybe I can just update elsticsuit with a composer?

**Comment by madonzy** [comment]
@romainruaud I did second way and it works!! Thank you!!

**Comment by romainruaud** [comment]
Fine !

You'll be able to switch back to our 2.3.x branch once @afoucret will have merged this.

Bes regards

**Comment by romainruaud** [comment]
Fixed by PR #397 . Please wait for the next minor 2.3 release or feel free to use the 2.3.x branch while waiting for it.

Best regards,
