### ISSUE TITLE
Products are not shown in category and search page

### ISSUE THREAD

**Issue by ArturoI** [Smile-SA/elasticsuite#727]
### Preconditions
Magento Version :2.1.10 EE
ElasticSuite Version :2.3.10
Environment : prod and dev
Third party modules : Wyomind order export tool

### Steps to reproduce

After installing Smile/ElasticSuite(multi-site magento 2) some of the products are not shown any more on the storefront (some categories are empty), I disabled the extension and the products appear again (using Mysql as search engine). I tried to debug the issue without any success. It seems like the data it is not in the elastic search server.  Do you have any idea What I should take a look ? 

Thanks in advance

**Comment by afoucret** [comment]
Hi @ArturoI,

This issue have been fixed in the latest releases and you should use branches 2.4.x and 2.5.x.
Closed since already fixed.

**Comment by federivo** [comment]
@afoucret Is it possible to use version 2.4.x with a Magento 2.1.10 install? Or the only way around the issue is to upgrade Magento to 2.2?

**Comment by federivo** [comment]
Thank you @afoucret. I guess our best option right now will be to install 2.4.x, smoke test our installation and give it a try. It will be hard for us to upgrade to M2 2.2 right now due to project restrictions. 

Thanks again  :)

**Comment by ArturoI** [comment]
@afoucret I upgraded to Magento 2.2.2 and elastic suite to 2.5 and i am still have the same issue. I think that the error is at the moment of creating the indexes, maybe there is a condition or something like that that it is not satisfied by certain products. I will try to debug that part, could you please tell me, if  you know,which class should i take a look?
