### ISSUE TITLE
main.CRITICAL: Requested store is not found - log event

### ISSUE THREAD

**Issue by refueledinc** [Smile-SA/elasticsuite#874]
While reviewing this extension's https://github.com/Ethan3600/magento2-CronjobManager managed jobs, I see that `elasticsuite_index_log_event` is throwing errors. 

```
[2018-04-16 17:04:01] main.CRITICAL: Requested store is not found {"exception":"[object] (Magento\\Framework\\Exception\\NoSuchEntityException(code: 0): Requested store is not found at /home/[store_path]/vendor/magento/module-store/Model/StoreRepository.php:109)"} []
```

### Preconditions

Magento Version : 2.2.3

ElasticSuite Version : ^2.5.0

Environment : Developer

Third party modules : https://github.com/Ethan3600/magento2-CronjobManager 

### Steps to reproduce

1. Setup magento cron jobs or run indexing manually
2. Review exception log with debugger enabled
3. Note, rebuilding indexes did not resolve the issue. 

### Expected result

1. Log event without error

### Actual result

![capture](https://user-images.githubusercontent.com/6714989/38826202-1e4dffbe-417d-11e8-8767-c7f8031e1b16.PNG)

**Comment by romainruaud** [comment]
Hello @refueledinc 

Actually I do not reproduce your issue on latest 2.5.x branch.

I see you are using elasticsuite 2.5.0.

Please update to latest 2.5.7 version and tell us if this is still happening.

Also, could you please provide more details to your setup, especially if you are using a multi-store environment.

Regards

**Comment by afoucret** [comment]
Hi @refueledinc , @romainruaud,

This one should be fixed by the PR #871 merged yesterday on the 2.5.x branch. It should be part of the upcoming 2.5.8 maintenance release.

Can you confirm the patch solve your issue ?

**Comment by refueledinc** [comment]
@romainruaud sorry for my delay. Yes, I am using multi-store.

**Comment by refueledinc** [comment]
@afoucret is 2.5.8 not available via `composer require smile/elasticsuite:2.5.x-dev` ? It seems it's only pulling 2.5.7 from `a992f6e`

**Comment by refueledinc** [comment]
@romainruaud BTW, I was on 2.5.6 but updated to 2.5.7, but still have the issue.

**Comment by afoucret** [comment]
@refueledinc,

Version 2.5.8 is not released yet but it will be shortly.

To test it you can do :

```
 composer require smile/elasticsuite:2.5.x-dev@dev
```

**Comment by refueledinc** [comment]
Just an FYI, I disabled said third party cron module and still receive same errors in logs every minute as the cron runs.

**Comment by afoucret** [comment]
Do you have a full stacktrace instead of just `Requested store is not found ...` ?

**Comment by refueledinc** [comment]
I have not been able to find any other error related to it, but I'm still looking. Any recommendations?

**Comment by refueledinc** [comment]
With debug mode enabled:

```
[2018-04-19 14:25:23] main.INFO: Cron Job elasticsuite_index_log_event is run [] []
[2018-04-19 14:25:23] main.DEBUG: Request Body [null] []
[2018-04-19 14:25:23] main.INFO: Request Success: {"method":"HEAD","uri":"http://localhost:9200/pl-dev_pl_tracking_log_event_20180404","headers":{"Host":["localhost:9200"],"Content-Type":["application/json"],"Accept":["application/json"]},"HTTP code":200,"duration":0.005394} []
[2018-04-19 14:25:23] main.DEBUG: Response [""] []
[2018-04-19 14:25:23] main.ERROR: Cron Job elasticsuite_index_log_event has an error: Requested store is not found. [] []
```

**Comment by afoucret** [comment]
Two questions :
- Did you delete any website /store view recently ?
- How are you index alias configurés ?

**Comment by refueledinc** [comment]
1. This is a migration from M1. We used this tool https://www.ubertheme.com/magento-extensions-2-x/magento-2-data-migration-pro/ to do the data migration. We have used it many times on many stores without any major issues. Yes, we did delete a website, but from what I can tell from the database tables for website and store, the IDs are all correct. From the frontend all websites load fine and function as expected, the only issue we have found is with this cron. 

2.
![capture](https://user-images.githubusercontent.com/6714989/39044518-5cfc025e-445e-11e8-8a9f-b0d7a45c8b09.PNG)

**Comment by afoucret** [comment]
I am quite sure you have a bug related to deleted stores.
I will submit a PR on this.

**Comment by refueledinc** [comment]
Thank you for your continued support on this

**Comment by afoucret** [comment]
PR #889 fix this bug.

**Comment by afoucret** [comment]
PR have been merged in branch 2.5.x and will be part of the next bugfix release (2.5.9).
You can test it on the branch if you want.
